### ISSUE TITLE
Update runtime to 23.08

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/com.sublimetext.three#38] opened 2024-04-16 20:28 UTC
Please, if this Flatpak is still maintained, update its runtime to 23.08. The currently used 21.08 is outdated and not supported anymore. Thanks!

/cc @ptomato

**Comment by ptomato** [comment] 2024-04-17 17:31
Duplicate of #36, which is blocked on #37. Someone will have to figure that out first, or the upgrade is likely to break packages for all existing users.

**Closed as not planned by ptomato** 2024-04-17 17:31 UTC
